version: 2
jobs:
  test:
    docker:
      - image: golangci/golangci-lint:v1.16
    steps:
      - checkout
      - run: golangci-lint run -v
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build-workflow:
    jobs:
      - test
